#OAUTH_CONSUMER_KEY = "Q0ei55gbpFvSnTvCIqoyfQ33dW1vptIY6eCCJKfTLiNLEx6f5D" 
#OAUTH_CONSUMER_KEY = "Q0icGC2pmx7V81OpTVAImYpv6U5h9kggCaPdWkwaBWMI5g8d40"
#OAUTH_CONSUMER_SECRET = "EcfFQP4tUJMpcs2fcCy3KCegChPSuOxarBG9DP6G" 
#OAUTH_CONSUMER_SECRET = "zMbQjZPNnWQAYmeR6XHxV0uFXCCfgFAlDtsHMsz9"

#Quickbooks.sandbox_mode = true