# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  aws_access_key: "AKIAXSNWZLCTJGY5E3UE"
  aws_access_secret: "GpCjRs+vUMup6Mi3AkuwW6ooaMsDb35KPny12F6a"
  aws_es_endpoint: "https://search-search-luft-m3fargpzriqyyqs5pjpisaxjiy.us-west-1.es.amazonaws.com"
  secret_key_base: da57d501d05f76912ef8c3477f679c06032ba65ab39e952766d357da8d5bac7e920ef70f6df85bf51551e3a15a58b47e7b978831f43eb06962ef671b1b1c5623
test:
  secret_key_base: a90d1667a7d7a15d9bf720805251c59a67c278b431c25a22d67976437c829ec18755643e064a221fe372929f0e996f0c60211dccba1ecf02a260ba22a57cb5b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  aws_access_key: "AKIAXSNWZLCTJGY5E3UE"
  aws_access_secret: "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"
  aws_es_endpoint: "https://search-search-luft-m3fargpzriqyyqs5pjpisaxjiy.us-west-1.es.amazonaws.com"
  secret_key_base: 8d724c1a01c03800877c9ce507fd1deaa2e056174c4306925b6eb03bfe074eb9675d59d6b509c2b9bdac97523fc82535b67576b44c497b126370d9c2654b4308